const state={stories:[],candidates:[],filter:'All',query:'',favorites:new Set(JSON.parse(localStorage.getItem('stories-favorites')||'[]')),recent:JSON.parse(localStorage.getItem('stories-recent')||'[]')};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&bsol;','"':'&quot;'}[c]));
function save(){localStorage.setItem('stories-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('stories-recent',JSON.stringify(state.recent.slice(0,8)))}
function filters(){return ['All','Phase 3','Phase 2','Story stub','★ Favorites']}
function renderFilters(){$('#filters').innerHTML=filters().map(x=>`<button class="filter ${x===state.filter?'active':''}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}
function matches(s){const hay=[s.title,s.hook,s.whatHappened,s.humanAngle,s.actors,s.category,s.status,s.eventKey,s.source].join(' ').toLowerCase();return (state.filter==='All'||(state.filter==='★ Favorites'?state.favorites.has(s.id):s.stage===state.filter))&&hay.includes(state.query.toLowerCase())}
function statusClass(s){return s.stage==='Phase 3'?'phase3':s.stage==='Phase 2'?'phase2':'stub'}
const stageOrder={'Phase 3':0,'Phase 2':1,'Story stub':2};
function storyDate(s){const explicit=s.dateAdded||s.addedAt||s.createdAt||s.updated_at||s.created_at;if(explicit)return Date.parse(explicit)||0;const match=String(s.eventKey||'').match(/(20\d{2}-\d{2}-\d{2})/);return match?Date.parse(match[1]):0}
function storySort(a,b){const stageDiff=(stageOrder[a.stage]??99)-(stageOrder[b.stage]??99);if(stageDiff!==0)return stageDiff;return storyDate(b)-storyDate(a)}
function action(url,label,kind=''){return url?`<a class="action ${kind}" href="${esc(url)}" target="_blank" rel="noreferrer">${label} ↗</a>`:''}
function card(s){const id=s.id||String(s.story_id);const fav=state.favorites.has(id);const stage=s.stage||s.status||'Promoted';return `<article class="story-card"><div class="card-top"><span class="stage ${statusClass({...s,stage})}">${esc(stage)}</span><button class="favorite ${fav?'active':''}" data-favorite="${esc(id)}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'★':'☆'}</button></div><h3>${esc(s.title)}</h3><p class="hook">${esc(s.hook||s.whatHappened||`Origin: ${s.source||'Unknown source'}`)}</p><div class="card-meta"><span>${esc(s.source||'Unknown source')}</span>${s.origin_item_id?`<span>· item ${esc(s.origin_item_id)}</span>`:''}</div><div class="actions">${action(s.doc||s.google_doc_url,'Doc','primary')}${action(s.telegramTopicLink||s.telegram_thread_url,'Telegram','telegram')}${action(s.phase2Folder||s.research_folder_url,'Research')}${action(s.phase3Doc,'Visual script')}${action(s.source||s.origin_url,'Source')}</div></article>`}
function candidateCard(c){const gist=c.gist?`<p class="candidate-gist">${esc(c.gist)}</p>`:`<p class="candidate-gist muted">Gist ${esc(c.summary_status||'PENDING').toLowerCase().replace('_',' ')}.</p>`;const display=c.display_headline||c.headline;return `<article class="candidate-card"><div class="candidate-top"><span class="stage candidate">Candidate</span><span class="muted">${esc(c.status)} · ${esc(c.summary_status||'PENDING')}</span></div><h3 class="candidate-display-headline">${esc(display)}</h3><details class="candidate-original"><summary>Original headline</summary><p>${esc(c.headline)}</p></details><p class="candidate-meta"><strong>${esc(c.source)}</strong> · ${esc(c.date||'Undated')} · Lane ${esc(c.lane)}</p>${gist}<div class="actions">${action(c.source_link,'Source','primary')}</div></article>`}
function render(){const shown=state.stories.filter(matches).sort(storySort);$('#storyGrid').innerHTML=shown.map(card).join('');$('#resultsCount').textContent=`${shown.length} ${shown.length===1?'story':'stories'}`;$('#resultsHeading').textContent=state.query||state.filter!=='All'?state.filter:'Promoted stories';$('#emptyState').hidden=shown.length>0;const recent=state.recent.map(id=>state.stories.find(s=>(s.id||String(s.story_id))===id)).filter(Boolean);$('#recentSection').hidden=!recent.length;$('#recentGrid').innerHTML=recent.slice(0,4).map(card).join('');const candidates=state.candidates.filter(c=>{const hay=[c.display_headline,c.headline,c.gist,c.source,c.lane,c.status,c.summary_status].join(' ').toLowerCase();return hay.includes(state.query.toLowerCase())}).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#candidateGrid').innerHTML=candidates.map(candidateCard).join('');$('#candidateCount').textContent=`${candidates.length} ${candidates.length===1?'item':'items'}`;$('#storyCount').textContent=`${state.candidates.length} candidates · ${state.stories.length} promoted stories`}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){state.filter=f.dataset.filter;renderFilters();render();return}const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();return}const link=e.target.closest('a.action');if(link){const card=link.closest('.story-card');const s=state.stories.find(x=>card&&card.querySelector('[data-favorite]')?.dataset.favorite===(x.id||String(x.story_id)));if(s){state.recent=[s.id||String(s.story_id),...state.recent.filter(x=>x!==(s.id||String(s.story_id)))];save()}}});
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;$('#clearSearch').style.display=state.query?'block':'none';render()});$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';state.query='';$('#clearSearch').style.display='none';render()});$('#clearRecent').addEventListener('click',()=>{state.recent=[];save();render()});$('#themeToggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('stories-theme',dark?'light':'dark');$('#themeToggle').textContent=dark?'☼':'☾'});
async function init(){if(localStorage.getItem('stories-theme')==='dark'){document.documentElement.dataset.theme='dark';$('#themeToggle').textContent='☾'}try{const r=await fetch('./data/stories.json');const d=await r.json();state.stories=d.stories||[];state.candidates=d.recent_candidates||[];$('#updatedAt').textContent=`Registry export · ${d.generated_at||'recently'}`;renderFilters();render()}catch(e){$('#storyCount').textContent='Could not load story registry';$('#updatedAt').textContent='Check data/stories.json'}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});init();
