const state={stories:[],filter:'All',query:'',favorites:new Set(JSON.parse(localStorage.getItem('stories-favorites')||'[]')),recent:JSON.parse(localStorage.getItem('stories-recent')||'[]')};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&bsol;','"':'&quot;'}[c]));
function save(){localStorage.setItem('stories-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('stories-recent',JSON.stringify(state.recent.slice(0,8)))}
function filters(){return ['All','Phase 3','Phase 2','Story stub','★ Favorites']}
function renderFilters(){$('#filters').innerHTML=filters().map(x=>`<button class="filter ${x===state.filter?'active':''}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}
function matches(s){const hay=[s.title,s.hook,s.whatHappened,s.humanAngle,s.actors,s.category,s.status,s.eventKey].join(' ').toLowerCase();return (state.filter==='All'||(state.filter==='★ Favorites'?state.favorites.has(s.id):s.stage===state.filter))&&hay.includes(state.query.toLowerCase())}
function statusClass(s){return s.stage==='Phase 3'?'phase3':s.stage==='Phase 2'?'phase2':'stub'}
function action(url,label,kind=''){return url?`<a class="action ${kind}" href="${esc(url)}" target="_blank" rel="noreferrer">${label} ↗</a>`:''}
function card(s){const fav=state.favorites.has(s.id);return `<article class="story-card"><div class="card-top"><span class="stage ${statusClass(s)}">${esc(s.stage)}</span><button class="favorite ${fav?'active':''}" data-favorite="${esc(s.id)}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'★':'☆'}</button></div><h3>${esc(s.title)}</h3><p class="hook">${esc(s.hook||s.whatHappened||'Open the story record for details.')}</p>${s.humanAngle?`<p class="angle"><strong>Why it matters:</strong> ${esc(s.humanAngle)}</p>`:''}<div class="card-meta"><span>${esc(s.status||'Active')}</span>${s.rightsStatus?`<span>· ${esc(s.rightsStatus.split(';')[0])}</span>`:''}</div><div class="actions">${action(s.doc,'Doc','primary')}${action(s.telegram,'Telegram','telegram')}${action(s.phase2Folder,'Research')}${action(s.phase3Doc,'Visual script')}${action(s.source,'Source')}</div></article>`}
function render(){const shown=state.stories.filter(matches);$('#storyGrid').innerHTML=shown.map(card).join('');$('#resultsCount').textContent=`${shown.length} ${shown.length===1?'story':'stories'}`;$('#resultsHeading').textContent=state.query||state.filter!=='All'?state.filter:'All stories';$('#emptyState').hidden=shown.length>0;const recent=state.recent.map(id=>state.stories.find(s=>s.id===id)).filter(Boolean);$('#recentSection').hidden=!recent.length;$('#recentGrid').innerHTML=recent.slice(0,4).map(card).join('');$('#storyCount').textContent=`${state.stories.length} stories · ${state.stories.filter(s=>s.stage==='Phase 3').length} in visual scripting`}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){state.filter=f.dataset.filter;renderFilters();render();return}const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();return}const link=e.target.closest('a.action');if(link){const card=link.closest('.story-card');const s=state.stories.find(x=>card&&card.querySelector('[data-favorite]')?.dataset.favorite===x.id);if(s){state.recent=[s.id,...state.recent.filter(x=>x!==s.id)];save()}}});
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;$('#clearSearch').style.display=state.query?'block':'none';render()});$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';state.query='';$('#clearSearch').style.display='none';render()});$('#clearRecent').addEventListener('click',()=>{state.recent=[];save();render()});$('#themeToggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('stories-theme',dark?'light':'dark');$('#themeToggle').textContent=dark?'☼':'☾'});
async function init(){if(localStorage.getItem('stories-theme')==='dark'){document.documentElement.dataset.theme='dark';$('#themeToggle').textContent='☾'}try{const r=await fetch('./data/stories.json');const d=await r.json();state.stories=d.stories||[];$('#updatedAt').textContent=`Registry export · ${d.updated||'recently'}`;renderFilters();render()}catch(e){$('#storyCount').textContent='Could not load story registry';$('#updatedAt').textContent='Check data/stories.json'}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});init();
