const state={assets:[],category:'All',query:'',favorites:new Set(JSON.parse(localStorage.getItem('stories-favorites')||'[]')),recent:JSON.parse(localStorage.getItem('stories-recent')||'[]')};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&bsol;','"':'&quot;'}[c]));
function save(){localStorage.setItem('stories-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('stories-recent',JSON.stringify(state.recent.slice(0,8)))}
function categories(){return ['All',...new Set(state.assets.map(a=>a.category).filter(Boolean))]}
function renderFilters(){$('#filters').innerHTML=categories().map(c=>`<button class="filter ${c===state.category?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}
function matches(a){const hay=[a.title,a.category,a.type,a.description,...(a.tags||[])].join(' ').toLowerCase();return (state.category==='All'||a.category===state.category)&&hay.includes(state.query.toLowerCase())}
function card(a){const fav=state.favorites.has(a.id);return `<article class="asset-card"><div class="card-top"><span class="asset-type">${esc(a.type||'Link')}</span><button class="favorite ${fav?'active':''}" data-favorite="${esc(a.id)}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'★':'☆'}</button></div><h3>${esc(a.title)}</h3><p>${esc(a.description||'Open this asset')}</p><div class="card-bottom"><span class="tag">${esc((a.tags&&a.tags[0])||a.category||'General')}</span><a class="open-link" data-open="${esc(a.id)}" href="${esc(a.url)}" target="_blank" rel="noreferrer">Open ↗</a></div></article>`}
function render(){const filtered=state.assets.filter(matches);$('#assetGrid').innerHTML=filtered.map(card).join('');$('#resultsCount').textContent=`${filtered.length} ${filtered.length===1?'item':'items'}`;$('#resultsHeading').textContent=state.query||state.category!=='All'?`${state.category==='All'?'Results':state.category}`:'All assets';$('#emptyState').hidden=filtered.length>0;const recent=state.recent.map(id=>state.assets.find(a=>a.id===id)).filter(Boolean);$('#recentSection').hidden=recent.length===0;$('#recentGrid').innerHTML=recent.slice(0,4).map(card).join('');$('#assetCount').textContent=`${state.assets.length} assets · updated ${new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})}`;$('#resultsHeading').scrollIntoView({block:'nearest'})}
function openAsset(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);save()}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;renderFilters();render();return}const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();return}const open=e.target.closest('[data-open]');if(open){openAsset(open.dataset.open)}});
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;$('#clearSearch').style.display=state.query?'block':'none';render()});$('#clearSearch').addEventListener('click',()=>{$('#searchInput').value='';state.query='';$('#clearSearch').style.display='none';render()});$('#clearRecent').addEventListener('click',()=>{state.recent=[];save();render()});$('#themeToggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('stories-theme',dark?'light':'dark');$('#themeToggle').textContent=dark?'☼':'☾'});
async function init(){const saved=localStorage.getItem('stories-theme');if(saved==='dark'){$('#themeToggle').textContent='☾';document.documentElement.dataset.theme='dark'}try{const r=await fetch('./data/assets.json');const data=await r.json();state.assets=data.assets||[];$('#updatedAt').textContent=`Data updated ${data.updated||'recently'}`;renderFilters();render()}catch(err){$('#assetCount').textContent='Could not load assets';$('#updatedAt').textContent='Check data/assets.json'}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});init();
